import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
//    id("com.google.devtools.ksp")
}

android {
    buildFeatures {
        buildConfig true
    }

    //noinspection GradleDependency
    compileSdkVersion 34

    defaultConfig {
        applicationId "quebec.virtualite.unirider"
        minSdkVersion 28
        //noinspection EditedTargetSdkVersion,OldTargetApi
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        testApplicationId "quebec.virtualite.unirider.test"
        testInstrumentationRunner "quebec.virtualite.unirider.test.CucumberInstrumentationRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            testCoverageEnabled true
        }
    }

    flavorDimensions "version"

    productFlavors {
        end2end {
            buildConfigField 'String', 'SCENARIOS', '"@End2End"'

            buildConfigField 'Boolean', 'BLUETOOTH_ACTUAL', 'true'

            // Calls the backend
            // Equivalent to localhost, which doesn't work with unmocked Retrofit2 request
            buildConfigField 'String', 'SERVER_BASE_URL', '"http://10.0.2.2:8080"'
            buildConfigField 'Boolean', 'SERVER_ACTUAL', 'true'
        }

        integration {
            buildConfigField 'String', 'SCENARIOS', '"~@End2End"'

            buildConfigField 'Boolean', 'BLUETOOTH_ACTUAL', 'false'

            // Backend is mocked
            buildConfigField 'String', 'SERVER_BASE_URL', '"http://localhost:8080"'
            buildConfigField 'Boolean', 'SERVER_ACTUAL', 'false'
        }
    }

    sourceSets {
        androidTest {
            assets.srcDirs = ['src/androidTest/assets']
            java.srcDirs = ['src/androidTest/kotlin']
        }

        main {
            java.srcDirs = ['src/main/kotlin']
        }

        test {
            java.srcDirs = ['src/test/kotlin']
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    namespace "quebec.virtualite.unirider"
    testNamespace "quebec.virtualite.unirider.test"
    lint {
        abortOnError false
    }
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    // App dependencies
    implementation "androidx.annotation:annotation:$androidxAnnotationVersion"
    implementation "androidx.navigation:navigation-fragment-ktx:$androidxNavigationVersion"
    implementation "androidx.navigation:navigation-ui-ktx:$androidxNavigationVersion"
    implementation "com.google.android.material:material:$androidMaterialVersion"

    // Database
    implementation "androidx.room:room-runtime:$roomVersion"
    //noinspection KaptUsageInsteadOfKsp
    kapt "androidx.room:room-compiler:$roomVersion"
//    ksp("androidx.room:room-compiler:$roomVersion")
    implementation "androidx.room:room-ktx:$roomVersion"

    // Unit Tests
    testImplementation "junit:junit:$junitVersion"
    testImplementation "org.mockito:mockito-inline:$mockitoInlineVersion"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion"

    // Integration Tests
    androidTestImplementation "androidx.test:core:$coreVersion"
    androidTestImplementation "androidx.test:core-ktx:$coreVersion"
    androidTestImplementation "androidx.test.ext:junit:$extJUnitVersion"
    androidTestImplementation "androidx.test.ext:junit-ktx:$extJUnitVersion"
    androidTestImplementation "androidx.test:runner:$runnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
    androidTestImplementation "com.android.support:support-annotations:$supportAnnotationsVersion"
    androidTestImplementation "androidx.test:rules:$rulesVersion"
//    androidTestImplementation 'com.android.support.test:rules:1.0.2'

    // Cucumber
    androidTestImplementation "io.cucumber:cucumber-android:$cucumberVersion"
    androidTestImplementation "io.cucumber:cucumber-picocontainer:$cucumberPicoVersion"

    // Jackson
    implementation "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-core:$jacksonVersion"
    implementation "com.fasterxml.jackson.core:jackson-annotations:$jacksonAnnotationVersion"
}
